#! /bin/bash

# (c) 2022- Spiros Papadimitriou <spapadim@gmail.com>
#
# This file is released under the MIT License:
#    https://opensource.org/licenses/MIT
# This software is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied.

# This file is required by gradescope, and will be copied
# to the abs path /autograder/run_autograder. It's executed
# within a fresh container instance, to grade one submission.

# Fail with error if not running in Docker or a VM (AWS?)..
if ! grep -sq ':/\(docker\|lxc\|ecs\)' /proc/1/cgroup; then
  echo "ERROR: Not running in a container or VM!" 1>&2
  exit 1
fi

set -x  # xtrace on

# All files (incl. this, i.e., setup.sh) will remain
# within abs path /autograder/source on the Docker image
export AUTOGRADER_ROOT=/autograder/source
cd ${AUTOGRADER_ROOT}
. etc/util.sh
. etc/env.sh

pyenv_init  # pyenv-installer doesn't modify .bashrc, and neither do we...

export PYTHONPATH=$PYTHONPATH:/autograder/source

${PYTHON} -m pyscope.cli setup && \
  ${PYTHON} -m pyscope.cli unittest

